03_django/06_django_axios/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<str:username>/', views.profile, name='profile'), # 이게 맨 위에 있으면 모든 주소에 대해 Page not found 에러 발생! => 문자열만 있는 url은 다른 url들을 먹어버림!! => 가장 아래에 작성!
]

03_django/06_django_axios/articles/urls.py
from django.urls import path
from . import views

app_name='articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/<int:comment_pk>/comments/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),
]

03_django/06_django_axios/myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')), # 우리의 accounts 보다 아래에 있어야 한다!!
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

03_django/06_django_axios/articles/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings # 모델에서 User 불러오기..

# Create your models here.
# Article 보다 위에 있어야 참조 가능!!!
class Hashtag(models.Model):
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content

class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 유저 모델 가져오기..
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True) # 비어있더라도 ''로 채워줌..
    hashtags = models.ManyToManyField(Hashtag, blank=True)

    class Meta:
        ordering = ('-pk',)   # 나중에 쓴 글이 위로오게한다..

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("articles:detail", kwargs={"article_pk": self.pk})
    
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-pk',)
    
    def __str__(self):
        return self.content

03_django/06_django_axios/articles/forms.py
from django import forms
from django.forms import ModelForm
from .models import Article, Comment
# class ArticleForm(forms.Form):
#     title = forms.CharField(
#         max_length=10,
#         label='제목',
#         widget=forms.TextInput(
#             attrs={
#                 'class': 'my-title',
#                 'placeholder': 'Enter the title',
#             }
#         )
#     )
#     content = forms.CharField(
#         label='내용',
#         widget=forms.Textarea(
#             attrs={
#                 'class': 'my-content',
#                 'placeholder': 'Enter the content',
#                 'rows': 5,
#                 'cols': 50,

#             }
#         )
#     ) # forms에는 textfield 없음..charfield에서 max_length 설정 안하면 됨.

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        max_length=10,
        widget=forms.TextInput(
            attrs={
                'class': 'my-title',
                'placeholder': 'Enter the title'
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'my-content',
                'placeholder': 'Enter the content',
                'rows': 5,
                'cols': 50,

            }
        )
    ) 
    class Meta:
        model = Article # model은 article에서 가져온다.
        # fields = ('title', 'content',)
        fields = ('title', 'content',) # field는 전체를 다 쓸 것이다...
        # exclude = ('title',)
        # Meta 태그 위에 쓰는 것을 권장.
        # widgets = {
        #     'title': forms.TextInput(attrs={
        #         'class': 'my-title'
        #     })
        # }

class CommentForm(forms.ModelForm):
    # content = forms.CharField(max_length=50)
    class Meta:
        model = Comment
        fields = ['content']

03_django/06_django_axios/articles/views.py
import hashlib
from django.http import JsonResponse, HttpResponseBadRequest
from IPython import embed
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.http import Http404, HttpResponse
from django.views.decorators.http import require_POST  # post 요청만 받아준다..
from .models import Article, Comment, Hashtag
from .forms import ArticleForm, CommentForm

# Create your views here.


def index(request):
    # GRATAVAR
    # filter 작성하면 여기서 작성할 필요없음!!
    # if request.user.is_authenticated:
    #     gravatar_url = hashlib.md5(request.user.email.encode('utf-8').lower().strip()).hexdigest
    # else:
    #     gravatar_url = None

    # SESSION
    # 사용자가 사이트에 몇번 방문하는지 count 하기
    # session에 visits_num 키로 접근해 값을 가져온다.
    # 기본적으로 존재하지 않는 키이기 때문에 키가 없다면(방문한적이 없다면) 0 값을 가져오도록 한다.
    # 해당 키(visits_num 가 없다면 새로 만들면서 0으로가져온다.
    visits_num = request.session.get('visits_num', 0)
    # 그리고 가져온 값을 session에 visits_num에 매번 1 씩 증가한 값으로 할당한다. (유저의 다음 방문을 위해 count 누적시킴)
    request.session['visits_num'] = visits_num + 1
    # admin 에서 로그아웃 하고 다시 들어가면 이전 count가 누적 되지 않고 새롭게 count 된다.
    # 누적시키고 싶으면 "https://docs.djangoproject.com/en/2.2/topics/http/sessions/" 참고하기....
    # session data 안에 있는 새로운 정보를 수정했다면 django 는 수정한 사실을 알아채지 못하기 때문에 다음과 같이 설정한다.
    request.session.modified = True

    articles = Article.objects.all()  # model에서 meta로 ordering 미리 해줌...(이미 역순으로 가져온다)
    # articles = get_list_or_404(Article) # 글이 하나도 없으면 에러 뜸.....
    context = {'articles': articles, 'visits_num': visits_num, }
    return render(request, 'articles/index.html', context)


@login_required  # 로그인된 사람만 create로 접근가능함
def create(request):
    # embed()
    if request.method == 'POST':
        # forms 작성 전
        # title instance
        # title = request.POST.get('title') # post로 들어오는 title 저장
        # content = request.POST.get('content')
        # article = Article(title=title, content=content)
        # article.save()

        # forms 작성 후
        # form 인스턴스를 생성하고 요청에 의한 데이터를 인자로 받는다.(binding 작업)
        # 이 처리과정은 binding이라고 불리며 유효성 체크를 할 수 있도록 해준다.
        # 인스턴스 생성(통째로 받아온다... -> FORM이 데이터에 맞춰서 알아서 매칭해줌)
        form = ArticleForm(request.POST)
        # article_form = get_user_model()
        # form이 유효한지 체크한다.(유효성 검사)
        if form.is_valid():
            # article = form.save() # 유효성 검사후 저장만 하면 된다(어느 필드에 있는지 model form을 쓰면 알게됨!)
            article = form.save(commit=False)   # article 객체만 만들고 저장은 안함
            article.user = request.user   # 왜래키값을 받고 저장!
            article.save()
            # hashtag 시작점 (글이 작성 된 후 써야하므로!)
            # 원래 있던 hashtag인지 아닌지 판단할 필요 있음.(get_or_create => 기존에 있다면 get, 없다면 create)
            for word in article.content.split():  # article의 content를 공백 기준으로 리스트로 변경
                if word.startswith('#'):    # '#'으로 시작하는 요소만 선택
                    # 튜플로 나옴.../ word랑 같은 해시태그를 찾는데 있으면 기존 객체(.get), 없으면 새로운 객체를 생성(.create)
                    hashtag, created = Hashtag.objects.get_or_create(
                        content=word)
                    # hashtag만 쓰면 나중에 hashtag[0]으로 해야 저장된 hashtag값 가져올 수 있음.
                    article.hashtags.add(hashtag)

            # form.cleaned_data로 정제된 데이터를 받는다.
            # title = form.cleaned_data.get('title') # 데이터 받아 저장.
            # content = form.cleaned_data.get('content')
            # 유효성 검사 끝났으므로..save 할 필요없이 바로 저장..
            # article = Article.objects.create(title=title, content=content)
        # return redirect('articles:index') # 글 작성되면  detail로...
            # get_absolute_url 작성하면 인스턴스 객체에 바로 넣을 수 있음
            return redirect(article)
    else:
        form = ArticleForm()  # 인스턴스 생성
    # 상황에 따라 context에 넘어가는 2가지 form
    # 1. GET: 기본 form
    # 2. POST: 검증에 실패 후의 form(is_valid == False)
    context = {'form': form, }
    return render(request, 'articles/form.html', context)  # get 방식일때...


def detail(request, article_pk):
    # try:
    article = get_object_or_404(Article, pk=article_pk)  # 모델 객체, 인자(parameter)
    # except Article.DoesNotExist:    # DNE 에러 발생시 404에러 발생시키고 저 문구 띄워줌/
    #     raise Http404('No Article matches the given query.')
    comments = article.comment_set.all()  # 모델명_set 으로 article 의 모든 댓글 가져온다!!
    # get_user_model()로 가져온다!!, user의 번호가 필요(user_id => foreign key로 접근)
    person = get_object_or_404(get_user_model(), pk=article.user_id)
    comment_form = CommentForm()    # 댓글 폼(detail 에서 출력되야 하므로...여기 적어준다...)
    context = {'article': article, 'comment_form': comment_form,
               'comments': comments, 'person': person, }
    return render(request, 'articles/detail.html', context)


@require_POST
def delete(request, article_pk):
    if request.user.is_authenticated:  # 인증된 사용자만 delete 가능!!
        article = get_object_or_404(Article, pk=article_pk)
        if request.user == article.user:    # 자기가 작성한 글이면 삭제
            article.delete()
        else:
            return redirect(article)    # 자기 글이 아니면 삭제 불가능
    return redirect('articles:index')


@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:  # 작성자와 현재유저가 같아야 수정 가능!!!
        if request.method == "POST":
            # request, instance 둘다 적어줘야함
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                # model forms 설정하면 cleaned_data 필요없음!
                # article.title = form.cleaned_data.get('title')
                # article.content = form.cleaned_data.get('content')
                article.save()
                # hashtag 수정 => 기존 값 다 지우고 새로 만든다
                article.hashtags.clear()  # 기존 값 삭제
                # 새로 만들기
                for word in article.content.split():  # article의 content를 공백 기준으로 리스트로 변경
                    if word.startswith('#'):    # '#'으로 시작하는 요소만 선택
                        # 튜플로 나옴.../ word랑 같은 해시태그를 찾는데 있으면 기존 객체(.get), 없으면 새로운 객체를 생성(.create)
                        hashtag, created = Hashtag.objects.get_or_create(
                            content=word)
                        # hashtag만 쓰면 나중에 hashtag[0]으로 해야 저장된 hashtag값 가져올 수 있음.
                        article.hashtags.add(hashtag)
                return redirect(article)
        else:
            # ArticleForm 을 초기화 (이전에 DB에 저장된 데이터를 넣어준 상태)
            # form = ArticleForm(initial={'title': article.title, 'content': article.content,})# 이전 값들을 가져옴
            # __dict__ : article 객체 데이터를 딕셔너리 자료형으로 변환
            # form = ArticleForm(initial=article.__dict__)
            # model form쓰면 instance 로 이전 값 가져온다!!!
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')   # 동일 인물이 아니면 홈으로 보냄.
    # 1. POST : 검증에 실패한 form(오류 메세지도 포함된 상태)
    # 2. GET : 초기화된 form
    context = {'form': form, 'article': article, }
    # create랑 html 공유함!(둘 다 form을 사용하므로...)
    return render(request, 'articles/form.html', context)

# @login_required # @login_required 와 @require_POST를 함께 쓰면 login 에서 next로 넘어갈때 GET방식으로 넘어가게 되어 405에러 발생함...
@require_POST  # post 요청만 허용하고 나머지는 막음... / if 문으로 post, get 분기할 필요 없음!!
def comments_create(request, article_pk):
    if request.user.is_authenticated:
        comment_form = CommentForm(request.POST)  # 데이터 받아오기(인스턴스)
        # 유효성 검사
        if comment_form.is_valid():
            # commit=False
            # 객체를 create 하지만, db에 레코드는 작성하지 않는다.
            comment = comment_form.save(commit=False)
            comment.article_id = article_pk
            comment.user = request.user  # comment.user에 request.user 넣고 저장!
            comment.save()
    return redirect('articles:detail', article_pk)


@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
        return redirect('articles:detail', article_pk)  # 인증된 사용자

    # 인증안된 사용자 일때 (접근권한 없다는 에러 보여주기)
    return HttpResponse('You are Unauthorized', status=401)


@login_required
def like(request, article_pk):
    if request.is_ajax():
        article = get_object_or_404(Article, pk=article_pk)

        if article.like_users.filter(pk=request.user.pk).exists():
            article.like_users.remove(request.user)
            liked = False
        else:
            article.like_users.add(request.user)
            liked = True
        # user = request.user -> request.user를 user로 쓸 수 있음
        # 해당 게시글에 좋아요를 누른 사람들 중에서 현재 접속유저가 있다면 좋아요를 취소
        # 해당 게시글의 모든 좋아요를 가져와야한다.
        # if request.user in article.like_users.all(): # 해당 유저가 그 글의 게시글에 좋아요 했는지 확인
        #     article.like_users.remove(request.user) # 좋아요 취소(삭제)
        # else:
        #     article.like_users.add(request.user) # 좋아요
        context = {'liked': liked, 'count': article.like_users.count(), }
        return JsonResponse(context)
    else:
        return HttpResponseBadRequest


@login_required
def follow(request, article_pk, user_pk):  # article_pk 인자만 받아옴...
    # 게시글 유저(작성자)
    person = get_object_or_404(get_user_model(), pk=user_pk)
    # 접속 유저(로그인)
    user = request.user
    if person != user:  # 작성자와 로그인한 사람이 달라야 한다!
        # 내가(request.user) 게시글 유저(person.user) 팔로워 목록에 이미 존재한다면,
        # if user in person.followers.all(): 동일한 기능을 함.
        if person.followers.filter(pk=user.pk).exists():
            person.followers.remove(user)
        else:
            person.followers.add(user)
    return redirect('articles:detail', article_pk)


def hashtag(request, hash_pk):
    hashtag = get_object_or_404(Hashtag, pk=hash_pk)
    # hashtag가 달린 모든 게시글 가져오기 (최신글 순서로..)
    articles = hashtag.article_set.order_by('-pk')
    context = {'hashtag': hashtag, 'articles': articles, }
    return render(request, 'articles/hashtag.html', context)

03_django/06_django_axios/articles/templates/articles/_article.html
<!--for문 안에 있는 것임!!!!-->
<div class="card mb-3">
  <div class="card-header">
    작성자 : <a class="card-link" href="{% url 'accounts:profile' article.user %}">{{ article.user }}</a>
    <!--작성자의 profile로 가야한다.-->
  </div>
  <div class="card-body">
    <h5 class="card-title">글 제목 : {{ article.title }}</h5>
    <p class="card-text">{{ article.pk }}</p>
    <hr>
    <p class="card-text">
      {% if user in article.like_users.all %}
      <i class="fab fa-gratipay like-button" style="font-size: 20px; color: crimson;" data-id="{{ article.pk }}"></i>
      {% else %}
      <i class="fab fa-gratipay like-button" style="font-size: 20px; color: black;" data-id="{{ article.pk }}"></i>
      {% endif %}
      <span id="like-count-{{ article.pk }}">{{ article.like_users.all|length }}</span> 명이 이 글을 좋아합니다.
    </p>
    <a href="{{ article.get_absolute_url }}" class="btn btn-primary">DETAIL</a>
  </div>
</div>


<!--<p>작성자 : {{ article.user }}</p> -->
<!-- .user : user name이 나온다! -->

<!--<p>{{ article.like_users.all|length }}명이 이 글을 좋아합니다.</p> -->
<!-- article.like_users.all : 이 글에 좋아요를 누른 모든 사람들 -->

03_django/06_django_axios/articles/templates/articles/_follow.html
<div class="jumbotron text-center">
  {% with follows=person.follows.all followers=person.followers.all %}
  <h1 class="display-4">{{ person.username }}</h1> <!--article.user도 가능-->
  <p class="lead">
    팔로잉 : {{ follows|length }} / 팔로워 : {{ followers|length }}
  </p>
  <hr class="my-4">
  {% if user != article.user %} <!-- 게시글 유저와 로그인한 유저가 달라야 팔로우 가능!! -->
  {% if user in followers %}
    <a class="btn btn-primary btn-lg" href="{% url 'articles:follow' article.pk review.user.pk %}" role="button">Unfollow</a> <!-- person.pk 게시글 쓴 사람??-->
  {% else %}
    <a class="btn btn-primary btn-lg" href="{% url 'articles:follow' article.pk review.user.pk %}" role="button">follow</a>
  {% endif %}
  {% endif %}
  {% endwith %}
</div>

03_django/06_django_axios/articles/templates/articles/_nav.html
{% load gravatar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  {% if user.is_authenticated %}
  <a class="navbar-brand" href="{% url 'articles:index' %}"> <a class="navbar-brand" href="#">
      <img src="https://s.gravatar.com/avatar/{{ user.email|makemd5 }}?s=80" width="30" height="30"
        alt="gravatar">Hello, {{ user.username }}
    </a></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
    <li class="nav-item">
      <a href="{% url 'accounts:profile' request.user.username %}">내 프로필</a> <!-- request.user -->
    </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:update' %}">정보수정</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:change_password' %}">비번변경</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
      </li>
      <li class="nav-item">
        <form action="{% url 'accounts:delete' %}" method="post" style='display: inline;'>
          {% csrf_token %}
          <input type="submit" value="회원탈퇴" class="btn btn-danger">
        </form>
      </li>
    </ul>
  </div>
  {% else %}

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
      </li>
    </ul>
  </div>
  {% endif %}
</nav>




<!-- request는 어디서든 사용할 수 있음. -->

<!-- 인증 되었을 때 (request.user.is_authenticated) => request 생략 가능!! -->


<!--어떤 유저가 오든 해당 유저의 img_url 불러온다.-->


<!-- 비로그인 상태 -->

03_django/06_django_axios/articles/templates/articles/base.html
{% load bootstrap4 %}
{% load gravatar %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/0321ecdd79.js" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  {% bootstrap_css %}
  <title>Document</title>
</head>

<body>
  {% include 'articles/_nav.html' %}
  <div class="container">
    {% comment %}
    <!--
    {% if user.is_authenticated %}
    <h3>Hello, {{ user.username }}</h3>
    <a href="{% url 'accounts:logout' %}">[로그아웃]</a>
    {% else %}
    <a href="{% url 'accounts:login' %}">[로그인]</a>
    <a href="{% url 'accounts:signup' %}">[회원가입]</a>
    {% endif %}
--> {% endcomment %}
    <!-- request는 어디서든 사용할 수 있음. -->
    {% block content %}
    {% endblock content %}
  </div>
  {% bootstrap_javascript jquery='full' %}
</body>

</html>

03_django/06_django_axios/articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% load make_link %}
{% block content %}
  <h1>DETAIL</h1>
  <hr>
  <p>{{ article.user }}</p>
  <p>{{ article.pk }}</p>
  <p>{{ article.title }}</p>
  <!--<p>{{ article.content }}</p>-->

  <p>{{ article|hashtag_link|safe }}</p>
 
  <p>{{ article.created_at| date:"SHORT_DATE_FORMAT" }}</p>
  <p>{{ article.updated_at|date:"M, j, Y" }}</p>
<!-- 자기가 작성한 글이 아니면 수정, 삭제 못하게 해야한다. -->
{% if request.user == article.user %}
  <a href="{% url 'articles:update' article.pk %}">[UPDATE]</a>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
{% endif %}
  <hr>
  <!-- 댓글 출력 -->
  {% for comment in comments %}
    <div>댓글 {{ forloop.revcounter }} : {{ comment.content }}
    {% if request.user == comment.user %}
      <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST" style="display: inline;">
        {% csrf_token %}
        <input type="submit" value="DELETE">
      </form>
    {% endif %}
    </div>
  {% empty %}
    <p><b>댓글이 없습니다.</b></p>
  {% endfor %}
  <hr>
  <!-- 댓글 입력 form -->
  {% if request.user.is_authenticated %}
  <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
    {% csrf_token %}
    {{ comment_form }}
    <input type="submit" value="submit">
  </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인 하세요]</a>
  {% endif %}
  <hr>
  {% include 'articles/_follow.html' %}
  <hr>
  <a href="{% url 'articles:index' %}">[back]</a>
<hr>
{% endblock content %}

03_django/06_django_axios/articles/templates/articles/form.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% block content %}

  {% if request.resolver_match.url_name == 'create' %} <!-- create로 넘어오면...-->
  <h1>CREATE</h1>
  {% else %}
  <h1>UPDATE</h1>
  {% endif %}
  <form action="" method='POST'> <!-- action에 값 안보내면 현재 url에 post 방식으로 보낸다...-->
    {% csrf_token %}
    <!--
    <label for="title">TITLE</label>
    <input type="text" name="title" id="title"><br>
    <label for="content">CONTENT</label>
    <input type="text" name="content" id="content"><br>
    -->
    <!--
    {{ form.title.label_tag }}
    {{ form.title }}
    {{ form.content.labe_tag }}
    {{ form.content }}

    {% for field in form %}
      {{ field.labe_tag}}
      {{ field }}
    {% endfor %}
    -->
    {% bootstrap_form form layout="horizontal"%} <!-- view 에서 들어오는 form(context) -->
    {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
  </form>
  <hr>
  {% if request.resolver_match.url_name == 'create' %}
    <a href="{% url 'articles:index' %}">BACK</a>
  {% else %}
    <a href="{{ article.get_absolute_url }}">BACK</a>
  {% endif %}
{% endblock content %}

03_django/06_django_axios/articles/templates/articles/hashtag.html
{% extends 'articles/base.html' %}
{% block content %}

<div class="jumbotron jumbotron-fluid text-center my-2 text-white bg-dark">
  <div class="container">
    <h1 class="display-4">{{ hashtag.content }}</h1>
    
    <p class="lead">{{ articles|length }} 개의 게시글</p>
  </div>
</div>
<hr>
<h3 class="text-center">{{ hashtag.content }} 를 태그한 글</h3>
<div class="row">
{% for article in articles %}
  {% with like=article.like_users.all comments=article.comment_set.all %}
  <div class="col-4 my-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ article.title }}</h5>
        <p class="card-text">{{ like|length }} 명이 좋아요</p>
        <p class="card-text">{{ comments|length }} 개의 댓글</p>
        <a href="{% url 'articles:detail' article.pk %}" class='btn btn-success'>[보러가기]</a>
      </div>
    </div>
  </div>
  {% endwith %}
{% endfor %}
</div>
{% endblock content %}

03_django/06_django_axios/articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% block content %}
<h1>Articles</h1>
<p><b>당신의 방문 횟수 : {{ visits_num }} {% if visits_num == 1 or visits_num == 0 %} time {% else %} times {% endif %} </b>
</p>
{% if user.is_authenticated %}
<!-- 인증된 사용자 라면 new 보여줌 -->
<a href="{% url 'articles:create' %}">[NEW]</a>
<!--appname : url 이름-->
{% else %}
<a href="{% url 'accounts:login' %}">[새 글을 작성하려면 로그인하세요]</a>
{% endif %}
<hr>
{% for article in articles %}
{% include 'articles/_article.html' %}
{% endfor %}
<script>
    // 1. 각 게시글 별로 좋아요 버튼이 있으니 모두 선택해야 한다.
    const likebuttons = document.querySelectorAll('.like-button')

    // 2. forEach 를 사용해서 각각의 좋아요 버튼을 클릭
    likebuttons.forEach(button => {
        button.addEventListener('click', function (event) {
            //console.log(event)
            // event.target.dataset.id 의 value 는 data-id 값이 들어있다.
            const articleId = event.target.dataset.id
            // 해당 상세 게시글의 좋아요 요청을 보낸다.
            axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest'
            axios.defaults.xsrfCookieName = 'csrftoken'
            axios.defaults.xsrfHeaderName = 'X-CSRFToken'
            axios.post(`/articles/${articleId}/like/`)
                .then(response => {
                    document.querySelector(`#like-count-${articleId}`).innerText = response.data
                        .count
                    if (response.data.liked) {
                        // 좋아요 색깔을 빨갛게
                        event.target.style.color = 'crimson'
                    } else {
                        // 좋아요 색깔을 까맣게
                        event.target.style.color = 'black'
                    }
                })
                .catch(error => console.log(error))
        })
    })
</script>
{% endblock content %}