03_django/CRUD_TEMP/jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'
urlpatterns = [
    path('', views.index, name='index'),
    path('past_life/', views.past_life, name='past_life'),
]

03_django/CRUD_TEMP/jobs/models.py
from django.db import models

# Create your models here.
class Job(models.Model):
    name = models.CharField(max_length=20)
    past_job = models.TextField()

    

03_django/CRUD_TEMP/jobs/views.py
import requests
from pprint import pprint
from faker import Faker
from decouple import config
from django.shortcuts import render, redirect
from .models import Job
# from faker import Faker

# Create your views here.
def index(request):
    return render(request, 'jobs/index.html')

def past_life(request):
    # 사용자로부터 이름 데이터를 받음.
    name = request.POST.get('name')
    
    # db 에 매칭되는 name 가져오기
    # Job.objects.get(name=name)
    # .get() 이 더 간단하지만 해당 값이 없을 경우 에러가 발생하기 때문.
    # filter : 한개던 0개던 상관없이 무조건 쿼리셋으로 가져옴.(리스트 형식)
    person = Job.objects.filter(name=name).first()

    # db 에 person 이 있는지 없는지 판단
    if person: # db 에 기존 이름이 있다면, 
        past_job = person.past_job
    else: # db 에 기존 이름이 없다면(person 이 빈 쿼리셋(==False))
        faker = Faker()
        past_job = faker.job()
        person = Job(name=name, past_job=past_job) # 새로운 레코드를 추가한다.
        person.save()

    # GIPHY (past_job 을 API 에 요청을 보내서 응답을 받음)
    GIPHY_API_KEY = config('GIPHY_API_KEY')
    url = f'http://api.giphy.com/v1/gifs/search?api_key={GIPHY_API_KEY}&q={past_job}&limit=1'
    data = requests.get(url).json()
    try:
        image = data.get('data')[0].get('images').get('original').get('url')
    except IndexError:
        image = None





    context = {'person': person, 'image': image}
    return render(request, 'jobs/past_life.html', context)

03_django/CRUD_TEMP/jobs/templates/jobs/index.html
{% extends 'base.html' %}
{% block content %}
<h1>전생의 직업</h1><br>

<form action="{% url 'jobs:past_life' %}" method="POST">
  {% csrf_token %}
  <label for="name">NAME</label>
  <input type="text" name="name" id="name">
  <input type="submit" value="submit">
</form>


{% endblock  %}

03_django/CRUD_TEMP/jobs/templates/jobs/past_life.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ person.name }} 님의 전생은 {{ person.past_job }}입니다.</h1>
<img src="{{ image }}" alt="gif_img">


<a href="{% url 'jobs:index' %}">다시하기</a>
{% endblock  %}