pjt06/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

pjt06/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/update', views.update, name='update'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/review/', views.reviews_create, name='reviews_create'),

]

pjt06/movies/models.py
from django.db import models

# Create your models here.


class Movie(models.Model):
    title = models.CharField(max_length=50)
    title_en = models.CharField(max_length=50)
    audience = models.IntegerField()
    open_date = models.DateField()
    genre = models.CharField(max_length=50)
    watch_grade = models.CharField(max_length=50)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.title


class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    score = models.FloatField()

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.content

pjt06/movies/forms.py
from django import forms
from .models import Movie, Review

class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = '__all__'

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('content', 'score')

pjt06/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Review
from .forms import MovieForm, ReviewForm
# Create your views here.


def index(request):
    movies = Movie.objects.all()
    context = {'movies': movies, }
    return render(request, 'movies/index.html', context)


def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {'form': form}
    return render(request, 'movies/form.html', context)


def detail(request, movie_pk):
    movies = get_object_or_404(Movie, pk=movie_pk)
    review_form = ReviewForm()
    reviews = movies.review_set.all()
    context = {'movie': movies, 'review_form': review_form, 'reviews': reviews,}
    return render(request, 'movies/detail.html', context)

def update(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {'movie': movie, 'form':form}
    return render(request, 'movies/form.html', context)


def delete(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == 'POST':
        movie.delete()
    return redirect('movies:index')

def reviews_create(request, movie_pk):
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.movie_id = movie_pk
            review.save()
    return redirect('movies:detail', movie_pk)

pjt06/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="card mx-auto" style="width: 80%;">
<h1 class="text-center">[영화 상세 정보]</h1>
<img src="{{ movie.poster_url }}" class='d-block w-50 mx-auto' alt="poster">  <div class="card-body">
    <h5 class="card-title">{{ movie.title }}</h5>
    <p class="card-text"><p>영어 제목: {{ movie.title_en }}</p>
<p>관객수: {{ movie.audience }}</p>
<p>개봉일: {{ movie.open_date }}</p>
<p>장르: {{ movie.genre }}</p>
<p>관람등급: {{ movie.watch_grade }}</p>
<p>평점: {{ movie.score }}</p>
<p><a href="{{ movie.poster_url }}">원본 이미지 보러가기</a></p>
<p>내용: <br>{{ movie.description }}</p></p>
<hr>
{% for review in reviews %}
<p>{{ forloop.revcounter }}번째 리뷰</p>
<p>평점: {{ review.score }}</p>
<p>내용: {{ review.content }} </p>
<hr>
{% empty %}
<p>리뷰는 제작자에게 큰 힘이 됩니다.</p>
{% endfor %}
<form action="{% url 'movies:reviews_create' movie.pk %}" method='POST'>
{% csrf_token %}
{{ review_form }}
<input type="submit" value="submit">
</form>
<a href="{% url 'movies:index' %}"><button type="button" class="btn btn-danger"><span class="text-light">목록</span></button></a>
<a href="{% url 'movies:update' movie.pk %}"><button type="button" class="btn btn-primary"><span class="text-light">수정</span></button></a>

<form class='d-inline' action="{% url 'movies:delete' movie.pk %}" method='POST'>
  {% csrf_token %}
  <button type="submit" class="btn btn-warning"><span class="text-light">삭제</span></button>
</form>
  </div>
</div>
{% comment %} <img src="{{ movie.poster_url }}" class='d-block w-50 mx-auto' alt="poster"> {% endcomment %}
{% comment %} <p>제목: {{ movie.title }}</p> {% endcomment %}
{% comment %} <p>영어 제목: {{ movie.title_en }}</p>
<p>관객수: {{ movie.audience }}</p>
<p>개봉일: {{ movie.open_date }}</p>
<p>장르: {{ movie.genre }}</p>
<p>관람등급: {{ movie.watch_grade }}</p>
<p>평점: {{ movie.score }}</p>
<p>이미지 주소: <a href="{{ movie.poster_url }}">{{ movie.poster_url }}</a></p>
<p>줄거리: {{ movie.description }}</p> {% endcomment %}
{% comment %} <hr>
{% for review in reviews %}
<p>{{ forloop.revcounter }}번째 리뷰</p>
<p>평점: {{ review.score }}</p>
<p>내용: {{ review.content }} </p>
<hr>
{% empty %}
<p>댓글이 없어요...</p>
{% endfor %}
<form action="{% url 'movies:reviews_create' movie.pk %}" method='POST'>
{% csrf_token %}
{{ review_form }}
<input type="submit" value="submit">
</form>
<a href="{% url 'movies:index' %}"><button type="button" class="btn btn-danger"><span class="text-light">목록</span></button></a>
<a href="{% url 'movies:update' movie.pk %}"><button type="button" class="btn btn-primary"><span class="text-light">수정</span></button></a>

<form class='d-inline' action="{% url 'movies:delete' movie.pk %}" method='POST'>
  {% csrf_token %}
  <button type="submit" class="btn btn-warning"><span class="text-light">삭제</span></button>
</form> {% endcomment %}
{% endblock content %}

pjt06/movies/templates/movies/form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
{% if request.resolver_match.url_name == 'create' %}
<h1 class="text-center">CREATE</h1>
{% else %}
<h1 class="text-center">UPDATE</h1>
{% endif %}
{% if request.resolver_match.url_name == 'create' %}
<a href="{% url 'movies:index' %}"><button type="button" class="btn btn-info">뒤로 가기</button></a>
{% else %}
<a href="{% url 'movies:detail' movie.pk %}"><button type="button" class="btn btn-info">뒤로 가기</button></a>
{% endif %}
<hr>
<form action="" method='POST'>
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="d-inline btn btn-info">제출</button>
</form>
</div>
{% endblock content %}

pjt06/movies/templates/movies/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="m-0" style="background-image: url('http://image14.hanatour.com/uploads/2012/02/IMG_19961.jpg'); background-attachment: fixed; position: relative; background-size: cover; background-repeat: no-repeat; background-position: center; background-blend-mode: screen;">
<div class="container">
<h1 class="text-center text-dark">영화 목록</h1>
<hr>

<a href="{% url 'movies:create' %}"><button type="button" class="btn btn-secondary">새 영화 추가</button></a>
<hr>
{% comment %} <img src="{% static 'movies/images/sample_img.jpg' %}" alt="" class="bg-img img-fluid"> {% endcomment %}
{% for movie in movies %}
<a href="{% url 'movies:detail' movie.pk %}"><h2 class="d-inline text-dark">{{ movie.title }}</h2><h5 class="d-inline text-dark">({{ movie.title_en }}, {{ movie.open_date.year }})</h5></a>

<h6><p>평점: {{ movie.score }}</p></h6>
<form action="{% url 'movies:delete' movie.pk %}" method='POST'>
  {% csrf_token %}
  <button type="submit" class="btn btn-secondary">삭제</button>
</form>
<hr>
{% endfor %}
</div>
{% endblock content %}