03_django/03_django_form/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/',
         views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/',
         views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),
]

03_django/03_django_form/articles/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
# Create your models here.


class Hashtag(models.Model):  # Article에 hashtags 때문에 Article 보다 상위에 있어야한다.
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content


class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)
    hashtags = models.ManyToManyField(Hashtag, blank=True)

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("articles:detail", kwargs={"article_pk": self.pk})


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return self.content

03_django/03_django_form/articles/templates/articles/_article.html
<div class="card mb-3">
  <div class="card-header">
    작성자: <a class="card-link" href="{% url 'accounts:profile' article.user %}">{{ article.user }}</a>
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ article.title }}</h5>
    <p class="card-text">{{ article.pk }}</p>
    <hr>
    <p class="card-text">
      <a href="{% url 'articles:like' article.pk %}">
        {% if  user in article.like_users.all %}
        <i class="fas fa-heart" style="color: crimson;"></i>
        {% else %}
        <i class="far fa-heart"></i>
        {% endif %}
      </a>
      <p>{{ article.like_users.all|length }}명이 이 글을 좋아합니다.</p>
      <a href="{{ article.get_absolute_url }}">[DETAIL]</a>
      <hr>
    </p>
    <a href="{{ article.get_absolute_url }}" class="btn btn-primary">DETAIL</a>
  </div>
</div>

03_django/03_django_form/articles/templates/articles/_follow.html
<div class="jumbotron text-center">
  {% with followers=person.followers.all following=person.followings.all %}
  <h1 class="display-4">{{ person.username }}</h1>
  <p class="lead">
    팔로잉 : {{ followings|length }} / 팔로워 : {{ followers|length }}
  </p>
  <hr class="my-4">
  {% if user != article.user %}
  {% if user in   followers %}
  <a class="btn btn-primary btn-lg" href="{% url 'articles:follow' article.pk person.pk %}" role="button">Unfollow</a>
  {% else %}
  <a class="btn btn-primary btn-lg" href="{% url 'articles:follow' article.pk person.pk %}" role="button">follow</a>
  {% endif %}
  {% endif %}
  </p>
  {% endwith %}
</div>

03_django/03_django_form/articles/templates/articles/_nav.html
  {% load gravatar %}
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
    {% if user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'articles:index' %}"><a class="navbar=brand" href="#">
        <img src="https://s.gravatar.com/avatar/{{ user.email|makemd5 }}?s=80" width="30" height="30" alt="gravatar">
        Hello, {{ user.username }}
      </a></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:profile' user.username %}">내 프로필</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:update' %}">정보 수정</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:change_password' %}">비번 변경</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
        </li>
        <li class="nav-item">
          <form action="{% url 'accounts:delete' %}" method="POST" style="display: inline">
            {% csrf_token %}
            <input type="submit" value="회원탈퇴" class="btn btn-danger">
          </form>
        </li>
      </ul>
    </div>
    {% else %}
    <a class="navbar-brand" href="{% url 'articles:index' %}"><a class="navbar=brand" href="#">
        <img src="https://s.gravatar.com/avatar/{{ user.email|makemd5 }}?s=80" width="30" height="30" alt="gravatar">
        Hello, Stranger !!!
      </a></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
        </li>
      </ul>
    </div>
    {% endif %}
  </nav>

03_django/03_django_form/articles/templates/articles/base.html
{% load bootstrap4 %}
{% load gravatar %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/d749212f5f.js" crossorigin="anonymous"></script>
  {% bootstrap_css %}
  <title>Document</title>
</head>

<body>
  {% include 'articles/_nav.html' %}
  <div class="container">
    {% block content %}
    {% endblock  %}
    {% bootstrap_javascript jquery='full' %}
  </div>
</body>

</html>

03_django/03_django_form/articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% load make_link %}
{% load bootstrap4 %}
{% block content %}
<h1>DETAIL</h1>
<hr>
<p>{{ article.user }}</p>
<p>{{ article.pk }}</p>
<p>{{ article.title }}</p>
<p>{{ article|hashtag_link|safe }}</p>
<p>{{ article.created_at|date:"SHORT_DATETIME_FORMAT" }}</p>
<p>{{ article.updated_at|date:"M, j ,Y" }}</p>
{% if request.user == article.user %}
<a href="{% url 'articles:update' article.pk %}" class="btn btn-info">UPDATE</a>
<form action="{% url 'articles:delete' article.pk %}" method="POST">
  {% csrf_token %}
  <input type="submit" value="delete" class="btn btn-danger">
</form>
{% endif %}
<hr>
<!-- 댓글 출력 -->
{% for comment in comments %}
<div>
  <span>{{ comment.user }}의 댓글: {{ comment.content }}</span>
  {% if request.user == comment.user %}
  <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST" style="display-inline">
    {% csrf_token %}
    <input type="submit" value="delete" class="btn btn-danger">
    {% endif %}
  </form>
</div>


{% empty %}
<p><b>댓글이 없습니다.</b></p>
{% endfor %}
<hr>
<!-- 댓글 입력 form -->
{% if user.is_authenticated %}
<form action="{% url 'articles:comments_create' article.pk %}" method="POST">
  {% csrf_token %}
  {{ comment_form }}
  <input type="submit" value="submit" class="btn btn-primary">
</form>
{% else %}
<a href="{% url 'accounts:login' %}">댓글을 작성하려면 로그인하세요</a>
{% endif %}
{% include 'articles/_follow.html' %}
<a href="{% url 'articles:index' %}" class="btn btn-warning">back</a>
{% endblock  %}

03_django/03_django_form/articles/templates/articles/form.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% block content %}

{% if  request.resolver_match.url_name == 'create' %}
<h1>CREATE</h1>
{% else %}
<h1>UPDATE</h1>
{% endif %}
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form layout="horizontal" %}
  {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
  {% comment %} <input type="submit" value="제출"> {% endcomment %}
  {% comment %} {{ form.title.label_tag }}
  {{ form.title }}
  {{ form.content.label_tag }}
  {{ form.content}} {% endcomment %}

  {% comment %} {% for field in form %}
  {{ field.label_tag }}
  {{ field }}
  {% endfor %}
  {{ form.as_p }} {% endcomment %}
  {# <input type="text" name="title" id="title"><br> #}
  {# <label for="content">CONTETN</label> #}
  {# <input type="text" name="content" id="content"><br> #}
</form>
<hr>
{% if request.resolver_match.url_name == 'create' %}
<a href="{% url 'articles:index' %}">BACK</a>
{% else %}
<a href="{{ article.get_absolute_url }}">BACK</a>
{% endif %}
{% endblock  %}

03_django/03_django_form/articles/templates/articles/hashtag.html
{% extends 'articles/base.html' %}
{% block content %}

<div class="jumbotron jumbotron-fluid text-center my-2 text-white bg-dark">
  <div class="container">
    <h1 class="display-4">{{ hashtag.content }}</h1>
    <p class="lead">{{ articles|length }} 개의 게시글</p>
  </div>
</div>
<hr>
<h3 class="text-center">{{ hashtag.content }} 를 태그한 글</h3>
<div class="row">
  {% for article in articles %}
  {% with likes=article.like_users.all comments=article.comment_set.all %}
  <div class="col-4 my-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ article.title }}</h5>
        <p class="card-text">{{ likes|length }} 명이 좋아요</p>
        <p class="card-text">{{ comments|length }} 개의 댓글</p>
        <a href="{% url 'articles:detail' article.pk %}" class="btn btn-dark">디테일</a>
      </div>
    </div>
  </div>
  {% endwith %}
  {% endfor %}
</div>
{% endblock content %}

03_django/03_django_form/articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% block content %}
<h1>Article</h1>

<p><b>당신의 방문 횟수 : {{ visits_num }}{% if visits_num <= 1 %}time{% else %}times{% endif %}</b></p>
{% if user.is_authenticated %}
<a href="{% url 'articles:create' %}">[NEW]</a>
{% else %}
<a class="btn btn-warning" href="{% url 'accounts:login' %}" style="display: inline">글 작성하고 싶으면 로그인하던가~~</a>
<a class="btn btn-warning" href="{% url 'accounts:signup' %}" style="display: inline">글 작성하고 싶은데 아이디없으면 가입하던가~~</a>
{% endif %}
<hr>
{% for article in articles %}
{% include 'articles/_article.html' %}
{% endfor %}
{% endblock  %}